### PR TITLE
Ggplot2 materials

### PR DESCRIPTION
**Pull request by tamsinforbes**
adding ggplot2 materials with DownGit link and GitZip instructions refs

### CODE REVIEW

**Comment by willbowditch** [comment]
@tamsinforbes just as a git practice thing - you've started this branch from the GitZip branch. Meaning that the gitzip changes are part of the ggplot materials changes too. This is generally not the way it quite intended to work, generally always start from master and make edits for a particular thing on a branch. Then merge those back into master. 

```
| * dc726f0 (origin/ggplot2-materials) adding ggplot DownGit link                                                                TF, 6d ago
| * ce5ed06 adding ggplot materials                                                                                              TF, 6d ago
| * 218d358 (origin/gitzip-instructions) GitZip instructions fix typo                                                            TF, 6d ago
| * 2c3d197 GitZip instructions                                                                                                  TF, 6d ago
* |   f202eec (HEAD -> master, origin/master, origin/HEAD) Merge pull request #9 from departmentfortransport/stringr-materials   SW, 6d ago
|\ \
| |/
| * c2a73e6 (origin/stringr-materials) add stringr materials                                                                     TF, 6d ago
|/
| * af65ed5 (origin/update-schedule) Update README.md
```

So `git checkout master` (Change to master)
`git pull` (get the latest remote version)
`git checkout -b new_feature` (make a new branch, with master as the starting point)

**Comment by willbowditch** [comment]
The above 'Revert' commits undo the changes in those commits, but only on this branch. So this branch should now only contain the ggplot2 changes.

**Comment by willbowditch** [comment]
Removed the auto-installing tidyverse lines. In general, don't think we should script installation for people and if so, use the pacman package manager.

**Comment by willbowditch** [comment]
This plot produces an error and actually doesn't represent the data - the scale limits are not as wide as the data itself. 

```
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
    3.02    19.34    30.15    53.34    48.32 59970.00 
```

I don't think this code should be included in its current form. 

```
ggplot(data=df2017, aes(as.numeric(PluginDuration))) +
  geom_histogram(binwidth=5,colour="white", fill="#006853") +
  xlab("Length of plug-in time, mins") + 
  scale_x_continuous(limits=c(0,100),breaks=seq(0,100,10))+
  scale_y_continuous(breaks =seq(0,8000,2000),name=""
                     , labels=c("0","2,000","4,000","6,000", "8,000"))+
  ggtitle("Frequency")+theme_dft5
```

If we are trimming the data for the plot this should be obvious via a filter and the product of an error. 
```
ggplot(data=df2017 %>% filter(PluginDuration < 100), aes(PluginDuration)) +
  geom_histogram(binwidth=5,colour="white", fill="#006853") +
  xlab("Length of plug-in time, mins") + 
  # scale_x_continuous(limits=c(0,100),breaks=seq(0,100,10))+
  # scale_y_continuous(breaks =seq(0,8000,2000),name=""
  #                    , labels=c("0","2,000","4,000","6,000", "8,000"))+
  ggtitle("Frequency")+theme_dft5
```

**Comment by willbowditch** [comment]
Made a number of changes here - mostly removing errors but also changed the section on saving plots as the method employed here was outdated and not best practise. Recommendation is to use ggsave function with svg or png, avoiding jpeg as it is a lossy format.

**Review by willbowditch — APPROVED** [review]
Think it would be good if someone else checked this over before merging - made a number of changes, see comments.

**Comment by tamsinforbes** [comment]
good spot on the ggplot2 and gitzip muddle - did not intend to do that.

**Comment by tamsinforbes** [comment]
@willbowditch I've checked it and made a few minor changes (linting etc) think this is ready to merge into master

**Comment by willbowditch** [comment]
Cool will do so now @tamsinforbes  - thanks!

**Pull request merged**
