### PR TITLE
Gitzip instructions

### PR DESCRIPTION
**Pull request by tamsinforbes**
adding gitzip instructions on how to download a subfolder rather than the whole repo. This is also possible via a link with DownGit which I will use for ggplot2 - as it has no easily to create README

### CODE REVIEW

**Comment by willbowditch** [comment]
Hey @tamsinforbes - I see where you're going with this, people may not want to download a whole repo. Hadn't thought of that and it is an annoyance with github. 

Looking at the DownGit thing you've added to the ggplot2 one, I wonder if we should just do that for them. Not a big job to add a link to each README and saves the user having to install this plugin. What do you think? 

Instructions are good if you this option is easier, so will mark the PR as checked now 👍🏻

**Review by willbowditch — APPROVED** [review]
LGTM (see comment)

**Comment by tamsinforbes** [comment]
yep - I very much like the DownGit approach (also because it sounds like a
yoga pose) [unfortunately I found GitZip first and spent ages writing
instructions for it - and just about when I'd finished Dray goes and pops
up with DownGit... sigh, anyway I learnt how to make pink arrows (totes
transferable skill right?]

I have got into a right muddle with adding stuff to the repo and each time
cloning the whole thing and then having multiple copies of everything on
multiple branches... But if you want to contribute you have to clone the
whole lot?

**Comment by tamsinforbes** [comment]
so do you reckon we should dump the GitZip instructions (and pretty pictures with pink arrows) and got with DownGit throughout?

**Comment by willbowditch** [comment]
Okay @tamsinforbes - maybe we should delete this branch then Up to you as you've already written the instructions, but I guess we should choose one and go with it. I think, as the DownGit one doesn't require any installation of anything, it would be my preference. 

Alternative is to just provide the instructions and not have to add the link to each page, which is much less effort in the long run, but slightly harder for users. I'd probably just link to the downgit on the main readme of the repo and leave it as that. 

Yep, unfortunately the cloning the whole repo thing is part of git's design. You can do 'shallow clones' of a single branch, which means don't download all the history, just the latest version. See the `--depth` argument https://git-scm.com/docs/git-clone

As long as we don't store tons of large datasets in here it shouldn't get too unruly.

You shouldn't have to clone the repo multiple times, you should be able to checkout between branches within the same clone of a repo.

**Comment by tamsinforbes** [comment]
decided we don't want gitzip - downgit is better

**Pull request closed without merging**
